
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Social Compass Insights AI agent.
 *
 * - getSocialCompassInsights - A function that handles the process of analyzing social interaction logs and providing personalized insights.
 * - SocialCompassInsightsInput - The input type for the getSocialCompassInsights function.
 * - SocialCompassInsightsOutput - The return type for the getSocialCompassInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SocialCompassInsightsInputSchema = z.object({
  interactionLogs: z.string().describe('A detailed log of social interactions, including who, what, where, when, and subjective feelings before and after.'),
  userName: z.string().optional().describe('The name of the user, if available, to personalize the insights.'),
});
export type SocialCompassInsightsInput = z.infer<typeof SocialCompassInsightsInputSchema>;

const SocialCompassInsightsOutputSchema = z.object({
  insights: z.string().describe('Personalized insights derived from the social interaction logs, highlighting patterns and recommendations.'),
});
export type SocialCompassInsightsOutput = z.infer<typeof SocialCompassInsightsOutputSchema>;

export async function getSocialCompassInsights(input: SocialCompassInsightsInput): Promise<SocialCompassInsightsOutput> {
  return socialCompassInsightsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'socialCompassInsightsPrompt',
  input: {schema: SocialCompassInsightsInputSchema},
  output: {schema: SocialCompassInsightsOutputSchema},
  prompt: `You are an expert social dynamics analyst. You are assisting {{#if userName}}{{userName}}{{else}}the user{{/if}}.
Analyze the following social interaction logs to provide personalized insights about what drains or recharges {{#if userName}}{{userName}}{{else}}them{{/if}}.
Focus your analysis on the following aspects:

1.  **Impact of Individuals**:
    *   Identify patterns related to specific individuals mentioned in the "People Met" field.
    *   How do interactions with different people (e.g., Riya Sharma, John Doe) or groups of people tend to affect {{#if userName}}{{userName}}{{else}}the user{{/if}}'s energy levels (feelingBefore vs. feelingAfter)?
    *   Are there particular people who consistently energize or drain {{#if userName}}{{userName}}{{else}}the user{{/if}}?

2.  **Influence of Event Types**:
    *   Examine how different "Event Types" (including any custom event types specified when 'Other' is chosen) influence {{#if userName}}{{userName}}{{else}}the user{{/if}}'s energy.
    *   Are certain types of events (e.g., 'Work Meeting', 'Party', or a custom type like 'Hobby Club Meetup') generally more recharging or draining for {{#if userName}}{{userName}}{{else}}this user{{/if}}?

3.  **Vibe and Feeling Correlations**:
    *   Note any recurring "Vibes" or feelings associated with specific people or event types.

4.  **Actionable Recommendations**:
    *   Based on your analysis, provide clear, actionable recommendations.
    *   Help {{#if userName}}{{userName}}{{else}}the user{{/if}} understand their social patterns better.
    *   Suggest ways {{#if userName}}{{userName}}{{else}}they{{/if}} might manage their social energy more effectively, such as prioritizing certain interactions or preparing for potentially draining ones.

Use a friendly, encouraging, and insightful tone.

Social Interaction Logs:
{{{interactionLogs}}}`,
});

const socialCompassInsightsFlow = ai.defineFlow(
  {
    name: 'socialCompassInsightsFlow',
    inputSchema: SocialCompassInsightsInputSchema,
    outputSchema: SocialCompassInsightsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);

